# Generated by Django 3.2.20 on 2023-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('regions', models.CharField(max_length=100)),
                ('yields', models.CharField(max_length=100)),
                ('acreage_of_production', models.IntegerField()),
                ('description', models.TextField(max_length=350)),
            ],
        ),
    ]
