# Generated by Django 3.2.20 on 2023-08-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
