# Generated by Django 3.2.20 on 2023-08-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_crop_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='acreage_of_production',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(max_length=999),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Published')),
                ('region', models.CharField(choices=[('G', 'Global'), ('AF', 'Africa'), ('AS', 'Asia'), ('CR', 'Caribbean'), ('CA', 'Central America'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America'), ('O', 'Other')], default='G', max_length=2)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
