# Generated by Django 3.2.20 on 2023-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230811_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('results', models.TextField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='impacts',
            field=models.ManyToManyField(to='main_app.Impact'),
        ),
    ]
